In [ ]:
import pandas as pd

# Replace 'your_file.csv' with the path to your CSV file
df_all_communities_data = pd.read_csv('G:/My Drive/data_for_good/eclaireur/data_raw/all_communities_data.csv', delimiter=';')
df_marches_publics_norm = pd.read_csv('G:/My Drive/data_for_good/eclaireur/data_raw/marches_publics_normalized_data.csv', delimiter=';')
df_selected_communities = pd.read_csv('G:/My Drive/data_for_good/eclaireur/data_raw/selected_communities_data.csv', delimiter=';')
df_subventions_norm = pd.read_csv('G:/My Drive/data_for_good/eclaireur/data_raw/subventions_normalized_data.csv', delimiter=';')

df_list = ['all_communities_data', 'marches_publics_normalized_data', 'selected_communities_data', 'subventions_normalized_data']
dfs = [df_all_communities_data, df_marches_publics_norm, df_selected_communities, df_subventions_norm]


df = df_marches_publics_norm

C:\Users\huynh\AppData\Local\Temp\ipykernel_4468\3769268397.py:4: DtypeWarning: Columns (4,5,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_all_communities_data = pd.read_csv('G:/My Drive/data_for_good/eclaireur/data_raw/all_communities_data.csv', delimiter=';')
C:\Users\huynh\AppData\Local\Temp\ipykernel_4468\3769268397.py:5: DtypeWarning: Columns (1,2,7,8,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_marches_publics_norm = pd.read_csv('G:/My Drive/data_for_good/eclaireur/data_raw/marches_publics_normalized_data.csv', delimiter=';')
C:\Users\huynh\AppData\Local\Temp\ipykernel_4468\3769268397.py:7: DtypeWarning: Columns (1,2,3,4,6,7,11,12,13,14,16,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df_subventions_norm = pd.read_csv('G:/My Drive/data_for_good/eclaireur/data_raw/subventions_normalized_data.csv', delimiter=';')

In [ ]:
# for i, df in enumerate(dfs):
#     print(f"DataFrame: {df_list[i]}")
#     print(df.shape)
#     print(df.columns)
#     # print(df.head())

In [ ]:
# ### CHECK DATE DISTRIBUTION

# import pandas as pd

# # Convert 'datenotification' column to datetime format, coercing invalid dates to NaT
# df_marches_publics_norm['datenotification'] = pd.to_datetime(df_marches_publics_norm['datenotification'], errors='coerce')

# # Get the range of dates
# min_date = df_marches_publics_norm['datenotification'].min()
# max_date = df_marches_publics_norm['datenotification'].max()

# print(f"Date Range: {min_date} to {max_date}")

# # Check for rows with invalid dates
# invalid_dates = df_marches_publics_norm[df_marches_publics_norm['datenotification'].isna()]
# print(f"Rows with invalid dates:\n{invalid_dates}")

# import matplotlib.pyplot as plt

# # Convert 'datenotification' to datetime if not already done
# df_marches_publics_norm['datenotification'] = pd.to_datetime(df_marches_publics_norm['datenotification'], errors='coerce')

# # Extract the year
# df_marches_publics_norm['year'] = df_marches_publics_norm['datenotification'].dt.year

# # Plot the histogram
# df_marches_publics_norm['year'].dropna().hist(bins=100, edgecolor='black')
# plt.xlabel('Year')
# plt.ylabel('Frequency')
# plt.title('Histogram of Years in datenotification')
# plt.yscale('log')  # Set y-axis to logarithmic scale

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467119 entries, 0 to 467118
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0              467119 non-null  int64
 1   codecpv                 465456 non-null  object
 2   acheteur_nom            76522 non-null   object
 3   montant                 467119 non-null  float64
 4   datenotification        467119 non-null  object
 5   lieuexecution_typecode  467118 non-null  object
 6   acheteur_id             467119 non-null  int64
 7   lieuexecution_code      467117 non-null  object
 8   uid                     349563 non-null  object
 9   formeprix               467119 non-null  object
 10  datepublicationdonnees  465195 non-null  object
 11  lieuexecution_nom       466375 non-null  object
 12  objet                   467119 non-null  object
 13  nature                  467103 non-null  object
 14  dureemois               467119 non-null  int64
 15  procedure               466087 non-null  object
 16  id                      463227 non-null  object
 17  _type                   161909 non-null  object
 18  siren                   467119 non-null  int64
 19  nom                     467119 non-null  object
 20  type                    467119 non-null  object
 21  titulaires              466325 non-null  object
dtypes: float64(1), int64(4), object(17)
memory usage: 78.4+ MB
None

In [5]:
df.describe()

         Unnamed: 0       montant   acheteur_id     dureemois         siren
count  4.671190e+05  4.671190e+05  4.671190e+05  4.671190e+05  4.671190e+05
mean   5.477550e+05  1.901841e+08  2.174654e+13  5.516103e+01  2.174654e+08
std    2.568019e+05  5.828333e+10  1.340145e+12  1.772091e+04  1.340145e+07
min    0.000000e+00 -7.920000e+05  2.000002e+13  0.000000e+00  2.000002e+08
25%    3.629105e+05  4.860000e+04  2.106009e+13  8.000000e+00  2.106009e+08
50%    5.277150e+05  1.111425e+05  2.169012e+13  1.700000e+01  2.169012e+08
75%    7.858605e+05  3.200000e+05  2.233000e+13  4.800000e+01  2.233000e+08
max    1.000431e+06  3.436997e+13  2.497401e+13  1.210202e+07  2.497401e+08

In [6]:
df.describe(include=["object", "bool"])

,codecpv,acheteur_nom,datenotification,lieuexecution_typecode,lieuexecution_code,uid,formeprix,datepublicationdonnees,lieuexecution_nom,objet,nature,procedure,id,_type,nom,type,titulaires
count,465456,76522,467119,467118,467117,349563,467119,465195,466375,467119,467103,466087,463227,161909,467119,467119,466325
unique,11565,1711,2495,14,6475,252671,8,1905,28026,302917,10,13,359936,1,3262,9,140398
top,45000000-7,Département de la Manche,2021-12-21,Code postal,75056,None,Révisable,2019-08-23,Code postal,GROS OEUVRE,Marché,Procédure adaptée,20190000100,Marché,Paris,COM,['COLAS FRANCE']
freq,6912,926,990,290596,6613,75869,258386,1112,9251,225,250896,285290,173,161909,6612,227988,2002

In [ ]:
df
print(df.shape)
print(df.columns.tolist())
print(df.head(5))

In [ ]:
for column in df.columns:
    print(f'Column: {column}')
    missing_values = df[column].isnull().sum()
    print(f'Missing values: {missing_values}')
    print('\n')

In [ ]:
column = 'lieuexecution_typecode'
value_counts_type = df[column].value_counts()
missing_values_type = df[column].isnull().sum()
total_count = value_counts_type.sum() + missing_values_type

print(value_counts_type)
print('')
print(f'Missing values: {missing_values_type}')
print(f'Total : {total_count}')
print(f'Total as percent : {total_count*100 / df.shape[0]}')

In [ ]:
column = 'lieuexecution_code'
value_counts_type = df[column].value_counts()
missing_values_type = df[column].isnull().sum()
total_count = value_counts_type.sum() + missing_values_type

print(value_counts_type)
print('')
print(f'Missing values: {missing_values_type}')
print(f'Total : {total_count}')
print(f'Total as percent : {total_count*100 / df.shape[0]}')

In [ ]:
length_counts = df['lieuexecution_code'].astype(str).str.len().value_counts().sort_index()
print(length_counts)

# Count how many values are longer than 5 characters
longer_than_5 = df['lieuexecution_code'].astype(str).str.len() > 5
count_longer_than_5 = longer_than_5.sum()
print(f'Number of values longer than 5 characters: {count_longer_than_5}')

In [ ]:
### CHECK FOR VALUES THAT ARE 5 CHARACTERS OR SHORTER AND CONTAIN AT LEAST ONE NON-NUMERIC CHARACTER
pd.set_option('display.max_rows', None)

# Show all values that are 5 characters or shorter and contain at least one non-numeric character
filtered_values = df[df['lieuexecution_code'].astype(str).str.len() <= 100]
filtered_values = filtered_values[filtered_values['lieuexecution_code'].str.contains(r'\D')]

print(filtered_values.shape)

print(filtered_values['lieuexecution_code'].value_counts())
### CONCLUSION:  not worth correcting

In [ ]:
### FILTERING OUT INVALID VALUES

removed_count = 0
# Filter out all values that are over 5 digits
df_filtered = df[~((df['lieuexecution_code'].str.len() > 5))]
removed_count += df.shape[0]-df_filtered.shape[0]
print(f'rows removed:  {removed_count}')
print(f'Percent of original : {df_filtered.shape[0]/df.shape[0]*100}')
print('')

# Filter out all values that contains non-numeric characters
df_filtered = df_filtered[~((df['lieuexecution_code'].str.contains(r'\D')))]
print(f'rows removed:  {df.shape[0]-df_filtered.shape[0]-removed_count}')
print(f'Percent of original : {df_filtered.shape[0]/df.shape[0]*100}')
print('')
removed_count += df.shape[0]-df_filtered.shape[0]-removed_count

# Filter out all values that have 1 digit
df_filtered = df_filtered[~((df['lieuexecution_code'].str.len() == 1))]
print(f'rows removed:  {df.shape[0]-df_filtered.shape[0]-removed_count}')
print(f'Percent of original : {df_filtered.shape[0]/df.shape[0]*100}')
print('')
removed_count += df.shape[0]-df_filtered.shape[0]-removed_count

# Remove values that have exactly 3 characters, unless they are '971', '972', '973', '974', or '976'
allowed_values = ['971', '972', '973', '974', '976']
df_filtered = df_filtered[~((df_filtered['lieuexecution_code'].astype(str).str.len() == 3) & (~df_filtered['lieuexecution_code'].isin(allowed_values)))]
print(f'rows removed:  {df.shape[0]-df_filtered.shape[0]-removed_count}')
print(f'Percent of original : {df_filtered.shape[0]/df.shape[0]*100}')
print('')
removed_count += df.shape[0]-df_filtered.shape[0]-removed_count

# Remove values that have exactly 4 characters
df_filtered = df_filtered[~((df_filtered['lieuexecution_code'].astype(str).str.len() == 4))]
print(f'rows removed:  {df.shape[0]-df_filtered.shape[0]-removed_count}')
print(f'Percent of original : {df_filtered.shape[0]/df.shape[0]*100}')
print('')
removed_count += df.shape[0]-df_filtered.shape[0]-removed_count

# Remove values that begin with '96', '98', or '99'
df_filtered = df_filtered[~df_filtered['lieuexecution_code'].str.startswith(('96', '98', '99'))]
print(f'rows removed:  {df.shape[0]-df_filtered.shape[0]-removed_count}')
print(f'Percent of original : {df_filtered.shape[0]/df.shape[0]*100}')
print('')
removed_count += df.shape[0]-df_filtered.shape[0]-removed_count

# print(f'rows removed:  {df.shape[0]-df_filtered.shape[0]}')
print(f'Final % of original : {df_filtered.shape[0]/df.shape[0]*100}')

In [ ]:
# Check the length counts after filtering
length_counts = df_filtered['lieuexecution_code'].astype(str).str.len().value_counts().sort_index()
print(length_counts)

In [ ]:
# Show unique values that have exactly x character along with their counts
char_count = 5
x_char_values_counts = df_filtered[df_filtered['lieuexecution_code'].astype(str).str.len() == char_count]['lieuexecution_code'].value_counts()
print(x_char_values_counts.shape)
print(x_char_values_counts)

In [ ]:
# Filter values that have exactly 5 characters and start with '9'
filtered_values = df_filtered[(df_filtered['lieuexecution_code'].astype(str).str.len() == 5) & (df_filtered['lieuexecution_code'].str.startswith('99'))]
print(filtered_values.shape)
# Show unique values and their counts
unique_values_counts = filtered_values['lieuexecution_code'].value_counts()

print(unique_values_counts)

In [ ]:
# Function to determine the 'dept' value
def determine_dept(code):
    code_str = str(code)
    if len(code_str) <= 3:
        return code_str
    elif code_str.startswith('97'):
        return code_str[:3]
    else:
        return code_str[:2]

# Apply the function to create the new 'dept' column
df_filtered['dept'] = df_filtered['lieuexecution_code'].apply(determine_dept)

In [ ]:
print(df_filtered.shape[0])

In [ ]:
dept_mainland = [
    "01", "02", "03", "04", "05", "06", "07", "08", "09",
    "10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
    "2A", "2B", "21", "22", "23", "24", "25", "26", "27", "28", "29",
    "30", "31", "32", "33", "34", "35", "36", "37", "38", "39",
    "40", "41", "42", "43", "44", "45", "46", "47", "48", "49",
    "50", "51", "52", "53", "54", "55", "56", "57", "58", "59",
    "60", "61", "62", "63", "64", "65", "66", "67", "68", "69",
    "70", "71", "72", "73", "74", "75", "76", "77", "78", "79",
    "80", "81", "82", "83", "84", "85", "86", "87", "88", "89",
    "90", "91", "92", "93", "94", "95", "971", "972", "973", "974", "976"
]

# Remove rows where 'dept' value isn't in 'department_codes' list
df_filtered = df_filtered[df_filtered['dept'].isin(dept_mainland)]

print(df_filtered)

In [ ]:
print(f'Final % of original : {df_filtered.shape[0]/df.shape[0]*100}')

In [ ]:
# Show unique counts of 'dept'
unique_dept_counts = df_filtered['dept'].value_counts()
print(unique_dept_counts.shape)
print(unique_dept_counts.tail(10))

In [ ]:
column = 'lieuexecution_code'
first_two_digits = df[column].astype(str).str[:2]
# Filter out numeric values
string_values = first_two_digits[~first_two_digits.str.isdigit()]
value_counts_string_values = string_values.value_counts()
missing_values_string_values = string_values.isnull().sum()
total_count = value_counts_string_values.sum() + missing_values_string_values

print(value_counts_string_values)
print('')
print(f'Missing values: {missing_values_string_values}')
print(f'Total: {total_count}')
print(f'Total as percent: {total_count * 100 / df.shape[0]}')

In [ ]:
### CHECK COLUMN nom
column = 'nom'
value_counts_type = df[column].value_counts()
missing_values_type = df[column].isnull().sum()
total_count = value_counts_type.sum() + missing_values_type

print(value_counts_type)
print('')
print(f'Missing values: {missing_values_type}')
print(f'Total : {total_count}')
print(f'Total as percent : {total_count*100 / df.shape[0]}')

In [ ]:
### CHECK COLUMN type
column = 'type'
value_counts_type = df[column].value_counts()
missing_values_type = df[column].isnull().sum()
total_count = value_counts_type.sum() + missing_values_type

print(value_counts_type)
print('')
print(f'Missing values: {missing_values_type}')
print(f'Total : {total_count}')
print(f'Total as percent : {total_count*100 / df.shape[0]}')

In [ ]:
import geopandas as gpd
import matplotlib.pyplot as plt

In [ ]:
shapefile_path = 'G:/My Drive/data_for_good/eclaireur/departements-20140306-50m-shp/departements-20140306-50m.shp'
gdf = gpd.read_file(shapefile_path, encoding='ISO-8859-1')

In [ ]:
# Get the unique counts of 'dept' values
unique_dept_counts = df_filtered['dept'].value_counts().reset_index()
unique_dept_counts.columns = ['dept', 'count']

# Merge the counts with the GeoDataFrame
gdf = gdf.merge(unique_dept_counts, left_on='code_insee', right_on='dept', how='left')

# Filter out overseas departments from the GeoDataFrame
mainland_gdf = gdf[gdf['code_insee'].isin(department_codes)]

print(gdf.head())

# Plot the map
fig, ax = plt.subplots(1, 1, figsize=(10, 10))
mainland_gdf.boundary.plot(ax=ax)
mainland_gdf.plot(column='count', ax=ax, legend=True, cmap='OrRd', missing_kwds={"color": "lightgrey"})
plt.title('Count of dept values on a map of Mainland France')

# Set the extent to zoom in to mainland France
ax.set_xlim(-5, 10)
ax.set_ylim(41, 52)

plt.show()

In [ ]:
# Count how many 'montant' values are above 10^12

montant_log_max = 12

count_above_log_max = df_filtered[df_filtered['montant'] > 10**montant_log_max].shape[0]
print(f'Number of montant values above : {count_above_log_max}')

# List unique 'dept' and count for montant values above 10^12
unique_dept_counts_above_log_max = df_filtered[df_filtered['montant'] > 10**montant_log_max]['dept'].value_counts()
print(unique_dept_counts_above_log_max)

# df_filtered.nlargest(15, 'montant')

In [ ]:
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np

# Group by 'dept' and sum the 'montant' values
montant_sum_by_dept = df_filtered.groupby('dept')['montant'].sum().reset_index()
montant_sum_by_dept.columns = ['dept', 'montant_sum']

# Print the columns of montant_sum_by_dept to ensure the column names are correct
print("Columns of montant_sum_by_dept:", montant_sum_by_dept.columns)

# Print the columns of gdf to ensure the column names are correct
print("Columns of gdf before merge:", gdf.columns)

# Merge the summed 'montant' values with the GeoDataFrame
gdf = gdf.merge(montant_sum_by_dept, left_on='code_insee', right_on='dept', how='left')

# Print the columns of gdf after merge to check if 'montant_sum' is present
print("Columns of gdf after merge:", gdf.columns)

# Check if the merge was successful and the 'montant_sum' column exists
print(gdf.head())

# Apply logarithmic transformation to 'montant_sum'
if 'montant_sum' in gdf.columns:
    gdf['log_montant_sum'] = np.log1p(gdf['montant_sum'])  # Use log1p to handle zero values
else:
    raise KeyError("The 'montant_sum' column is not found in the GeoDataFrame.")

# Plot the map and zoom in to mainland France
fig, ax = plt.subplots(1, 1, figsize=(10, 10))
gdf.boundary.plot(ax=ax)
gdf.plot(column='log_montant_sum', ax=ax, legend=True, cmap='OrRd', missing_kwds={"color": "lightgrey"})
plt.title('Log scale sum of montant by dept on a map of France')

# Set the extent to zoom in to mainland France
ax.set_xlim(-5, 10)
ax.set_ylim(41, 52)

plt.show()

In [ ]:
import geopandas as gpd
import matplotlib.pyplot as plt

# Group by 'dept' and sum the 'montant' values
montant_sum_by_dept = df_filtered.groupby('dept')['montant'].sum().reset_index()
montant_sum_by_dept.columns = ['dept', 'montant_sum']

# Print the columns of montant_sum_by_dept to ensure the column names are correct
print("Columns of montant_sum_by_dept:", montant_sum_by_dept.columns)

# Print the columns of gdf to ensure the column names are correct
print("Columns of gdf before merge:", gdf.columns)

# Merge the summed 'montant' values with the GeoDataFrame
gdf = gdf.merge(montant_sum_by_dept, left_on='code_insee', right_on='dept', how='left')

# Print the columns of gdf after merge to check if 'montant_sum' is present
print("Columns of gdf after merge:", gdf.columns)

# Check if the merge was successful and the 'montant_sum' column exists
print(gdf.head())

# Calculate the 90th percentile of 'montant_sum'
if 'montant_sum' in gdf.columns:
    vmax = gdf['montant_sum'].quantile(0.90)
else:
    raise KeyError("The 'montant_sum' column is not found in the GeoDataFrame.")

# Plot the map and zoom in to mainland France
fig, ax = plt.subplots(1, 1, figsize=(10, 10))
gdf.boundary.plot(ax=ax)
gdf.plot(column='montant_sum', ax=ax, legend=True, cmap='OrRd', vmax=vmax, missing_kwds={"color": "lightgrey"})
plt.title('Sum of montant with cut off, by dept on a map of France')

# Set the extent to zoom in to mainland France
ax.set_xlim(-5, 10)
ax.set_ylim(41, 52)

plt.show()